export const RAYCAST = {
  WINDOW: {
    CENTER: "open -g 'raycast://extensions/raycast/window-management/center-half'",
    TOP: "open -g 'raycast://extensions/raycast/window-management/top-half'",
    BOTTOM: "open -g 'raycast://extensions/raycast/window-management/bottom-half'",
    LEFT: "open -g 'raycast://extensions/raycast/window-management/left-half'",
    RIGHT: "open -g 'raycast://extensions/raycast/window-management/right-half'",
    MAXIMIZE: "open -g 'raycast://extensions/raycast/window-management/maximize'",
    NEXT_DISPLAY: "open -g 'raycast://extensions/raycast/window-management/next-display'",
    PREVIOUS_DISPLAY: "open -g 'raycast://extensions/raycast/window-management/previous-display'",
    NEXT_DESKTOP: "open -g 'raycast://extensions/raycast/window-management/next-desktop'",
    PREVIOUS_DESKTOP: "open -g 'raycast://extensions/raycast/window-management/previous-desktop'",
    CUSTOM: (name: string) =>
      `open -g 'raycast://raycast/customWindowManagementCommand?name=${encodeURIComponent(name)}'`,
  },
  WINDOW_LAYOUTS: {
    REACT_NATIVE: 'React Native Dev',
  },
  SYSTEM: {
    DO_NOT_DISTURB: "open 'raycast://extensions/do-not-disturb/toggle'",
    CAMERA: "open 'raycast://extensions/raycast/system/open-camera'",
    EMOJI_SEARCH: "open 'raycast://extensions/raycast/emoji-symbols/search-emoji-symbols'",
    GOOGLE_SEARCH: "open 'raycast://extensions/mblode/google-search/index'",
    CLIPBOARD_HISTORY: "open 'raycast://extensions/raycast/clipboard-history/clipboard-history'",
    AI_CHAT: "open 'raycast://extensions/raycast/raycast-ai/ai-chat'",
    DISMISS_NOTIFICATIONS: "open 'raycast://script-commands/dismiss-notifications'",
    CONFETTI: "open 'raycast://extensions/raycast/raycast/confetti'",
  },
} as const;

export const URLS = {
  GOOGLE: "open 'https://google.com'",
  TWITTER: "open 'https://twitter.com'",
  HACKER_NEWS: "open 'https://news.ycombinator.com'",
  FACEBOOK: "open 'https://facebook.com'",
  REDDIT: "open 'https://reddit.com'",
  PERPLEXITY: "open 'https://perplexity.com'",
  GITHUB: "open 'https://github.com'",
  YOUTUBE: "open 'https://youtube.com'",
  LINKEDIN: "open 'https://linkedin.com'",
  CHATGPT: "open 'https://chatgpt.com'",
} as const;

export const APP_REGEXES = {
  ARC: '^company\\.thebrowser\\.Browser$',
  BEEPER: '^com\\.automattic\\.beeper\\.desktop$',
  BRAVE: '^com\\.brave\\.Browser$',
  CHROME: '^com\\.google\\.Chrome$',
  CURSOR: '^com\\.todesktop\\.230313mzl4w4u92$',
  DIA: '^company\\.thebrowser\\.dia$',
  GHOSTTY: '^com\\.ghostty\\.Ghostty$',
  LEXICON: '^com\\.rekord\\.cloud\\.lexicon$',
  SAFARI: '^com\\.apple\\.Safari$',
  VSCODE: '^com\\.microsoft\\.VSCode$',
  ZED: '^dev\\.zed\\.Zed$',
  ZEN: '^app\\.zen-browser\\.zen$',
} as const;

export const APP_NAMES = {
  AKIFLOW: 'Akiflow',
  ARC: 'Arc',
  BEEPER: 'Beeper Desktop',
  CHATGPT: 'ChatGPT',
  CHROME: 'Google Chrome',
  CURSOR: 'Cursor',
  DIA: 'DIA',
  DISCORD: 'Discord',
  FIGMA: 'Figma',
  FINDER: 'Finder',
  GHOSTTY: 'GHOSTTY',
  LEXICON: 'Lexicon',
  NOTION: 'Notion',
  PASSWORD_MANAGER: '1Password',
  PERPLEXITY: 'Perplexity',
  REFLECT: 'Reflect',
  SLACK: 'Slack',
  SPOTIFY: 'Spotify',
  SUPERHUMAN: 'Superhuman',
  TEAMS: 'Microsoft Teams',
  TEXTS: 'Texts',
  VSCODE: 'Visual Studio Code',
  WARP: 'Warp',
  ZED: 'Zed',
} as const;
